-- --------------------------------------------------------
-- Tabla: orders
-- --------------------------------------------------------
CREATE TYPE public.order_status AS ENUM (
  'pending',
  'in_progress',
  'completed',
  'cancelled'
);

CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  restaurant_id bigint REFERENCES public.restaurants(id) NOT NULL,
  total_price numeric NOT NULL,
  status public.order_status DEFAULT 'pending'::public.order_status NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow individual read access for orders"
ON public.orders
FOR SELECT
USING (auth.uid() = user_id);

-- --------------------------------------------------------
-- Tabla: order_items
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
  menu_item_id bigint REFERENCES public.menu_items(id) NOT NULL,
  quantity integer NOT NULL,
  price numeric NOT NULL
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow individual read access for order_items"
ON public.order_items
FOR SELECT
USING (auth.uid() = (SELECT user_id FROM orders WHERE id = order_id));
