-- migration_20251111_create_orders.sql

-- Create the orders table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    delivery_address TEXT NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    restaurant_id BIGINT REFERENCES restaurants(id)
);

-- Create the order_items table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    menu_item_id BIGINT REFERENCES menu_items(id),
    quantity INTEGER NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    customized_ingredients JSONB
);

-- Add comments to the tables and columns
COMMENT ON TABLE orders IS 'Stores customer order information.';
COMMENT ON COLUMN orders.status IS 'The current status of the order (e.g., pending, confirmed, out_for_delivery, delivered, canceled).';

COMMENT ON TABLE order_items IS 'Stores the individual items within an order.';
COMMENT ON COLUMN order_items.customized_ingredients IS 'A JSON object detailing any customizations to the menu item.';

-- Enable RLS for the new tables
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Create policies for orders
CREATE POLICY "Allow authenticated users to insert their own orders"
ON orders
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Allow users to view their own orders"
ON orders
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Allow admin users to manage all orders"
ON orders
FOR ALL
TO authenticated
USING (
  (SELECT role FROM profiles WHERE user_id = auth.uid()) = 'admin'
);

-- Create policies for order_items
CREATE POLICY "Allow users to view items in their own orders"
ON order_items
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM orders
    WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid()
  )
);

CREATE POLICY "Allow admin users to manage all order items"
ON order_items
FOR ALL
TO authenticated
USING (
  (SELECT role FROM profiles WHERE user_id = auth.uid()) = 'admin'
);
