-- Tabla para guardar las ubicaciones de los repartidores en tiempo real
CREATE TABLE IF NOT EXISTS public.delivery_driver_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT, -- Lo dejaremos simple por ahora, sin foreign key
  lat NUMERIC NOT NULL,
  lng NUMERIC NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Habilitar Row Level Security
ALTER TABLE public.delivery_driver_locations ENABLE ROW LEVEL SECURITY;

-- Permitir lectura pública para que la app pueda ver las ubicaciones
DROP POLICY IF EXISTS "Allow public read access" ON public.delivery_driver_locations;
CREATE POLICY "Allow public read access"
ON public.delivery_driver_locations
FOR SELECT
USING (true);

-- Permitir inserción y actualización (en un caso real, esto estaría más protegido)
DROP POLICY IF EXISTS "Allow insert and update" ON public.delivery_driver_locations;
CREATE POLICY "Allow insert and update"
ON public.delivery_driver_locations
FOR ALL
USING (true);
